[toolchain]
anchor_version = "0.31.1"
solana_version = "4.2.2"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
aipartner_presale = "AgBSRTVFzdjV9ChfqEEJhCca2mn11Unw1vtZsP3NhqmN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"
