[workspace]
members = [
    "programs/*"
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.89.0"

[workspace.dependencies]
indexmap = "=2.2.6"
hashbrown = "=0.14.5"
block-buffer = "=0.10.4"
cpufeatures = "=0.2.12"
crypto-common = "=0.1.6"
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"

[profile.release]
overflow-checks = false
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=37673d77-fa71-41d2-9572-b8d4defa5cee"
wallet = "/root/.config/solana/id.json"
