[workspace]
members = [
    "programs/*"
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.89.0"

[workspace.dependencies]
indexmap = "2.13.0"
hashbrown = "=0.16.1"
block-buffer = "=0.10.4"
cpufeatures = "=0.2.17"
crypto-common = "=0.1.7"
anchor-lang = "0.31.2"
anchor-spl = "0.31.2"
solana-program = "=2.1.14"
zeroize = "=1.6.0"
zeroize_derive = "=1.4.2"

[profile.release]
overflow-checks = false
lto = "fat"
codegen-units = 1
opt-level = "z"

[patch.crates-io]
blake3 = { git = "https://github.com/BLAKE3-team/BLAKE3", tag = "1.5.5" }
